name: CI/CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo o código
        uses: actions/checkout@v4.2.2

      - name: Login no DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Construção e Envio de imagem docker
        uses: docker/build-push-action@v4
        with:
          context: ./src
          push: true
          file: ./src/Dockerfile
          tags: |
            davidalmd/fake-shop:v${{ github.run_number }}
            davidalmd/fake-shop

  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo o código
        uses: actions/checkout@v4.2.2

      - name: Configurando o kubeconfig
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_KUBECONFIG }}

      - name: Realizando o deploy do cluster k8s
        uses: Azure/k8s-deploy@v5
        with:
          manifests: |
            k8s/deployment.yaml
          images: |
            davidalmd/fake-shop:v${{ github.run_number }}
