name: CI/CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo o código
        uses: actions/checkout@v4.2.2

      - name: Login no DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER.TOKEN }}

      - name: Construção e Envio de imagem docker
        uses: docker/build-push-action@v4
        with:
          context: ./src
          push: true
          file: ./src/Dockerfile
          tags: davidalmd/fake-shop:v3
